language: haskell
ghc: "7.8"
sudo: required
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libftgl-dev
script:
  - "cd hawt"
  - "cabal install --only-dependencies"
  - "cabal configure && cabal build && cabal install"
  - cd "../hawt-backend-glfw"
  - "cabal install --only-dependencies"
  - "cabal configure && cabal build && cabal install"
  - cd "../hawt-backend-glut"
  - "cabal install --only-dependencies"
  - "cabal configure && cabal build && cabal install"
  - cd "../opengl-ui-test"
  - "cabal install --only-dependencies"
  - "cabal configure && cabal build"
notifications:
  email: false
