language: haskell
ghc: 7.8
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y ftgl
install:
  - "cd hawt"
  - "cabal install --only-dependencies"
script:
  - "cabal configure && cabal build"
notifications:
  email: false
